apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook-applicationset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: spoc-cluster1
            url: https://C8240773D683C0C8D0F3C4E8C5A87241.gr7.us-east-1.eks.amazonaws.com
          - cluster: spoc-cluster2
            url: https://6765A1139BD377E6674D9817D3F6428D.gr7.us-east-1.eks.amazonaws.com
  template:
    metadata:
      name: guestbook-{{cluster}}
    spec:
      project: default
      source:
        repoURL: https://github.com/argoproj/argocd-example-apps.git
        targetRevision: HEAD
        path: guestbook
      destination:
        server: "{{url}}"
        namespace: default
